services:
  - type: web
    name: truestate-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://truestate-backend.onrender.com/api
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
